# see https://github.com/scalameta/sbt-native-image#generate-native-image-from-github-actions
name: Native Image
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  build-native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # if these are updated, also update the references below
        os: [macOS-12, ubuntu-22.04, windows-2022]
        include:
          - os: macOS-12
            uploaded_filename: scitzen-x86_64-apple-darwin
            local_path: /Users/runner/work/scitzen/scitzen/target/native-image/scitzen
          - os: ubuntu-22.04
            uploaded_filename: scitzen-x86_64-pc-linux
            local_path: /home/runner/work/scitzen/scitzen/target/native-image/scitzen
          - os: windows-2022
            uploaded_filename: scitzen-x86_64-pc-win32.exe
            local_path: D:\a\scitzen\scitzen\target\native-image\scitzen.exe
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
        continue-on-error: true
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image,js'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
      - run: git fetch --tags || true
      - name: generate native image
        run: sh make-native-image.sh
      - uses: actions/upload-artifact@master
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
