# see https://github.com/scalameta/sbt-native-image#generate-native-image-from-github-actions
name: Native Image
on:
  push:
    branches:
      - master
  pull_request:
  release:
    types: [published]
jobs:
  build-native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # if these are updated, also update the references below
        os: [macOS-11, ubuntu-20.04, windows-2019]
        include:
          - os: macOS-11
            uploaded_filename: scitzen-x86_64-apple-darwin
            local_path: cli/target/native-image/scitzen
          - os: ubuntu-20.04
            uploaded_filename: scitzen-x86_64-pc-linux
            local_path: cli/target/native-image/scitzen
          - os: windows-2019
            uploaded_filename: scitzen-x86_64-pc-win32.exe
            local_path: cli\target\native-image\scitzen.exe
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v6
        continue-on-error: true
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: '22.0.0'
          java: 'java17'
      - uses: coursier/setup-action@v1
        with:
          apps: sbt
      - run: git fetch --tags || true
      - name: generate native image (linux)
        run: sbt nativeImage
        shell: bash
        if: ${{ matrix.os != 'windows-2019' }}
        env:
          JAVA_OPTS: -Xmx1g
      - name: generate native image (windows)
        shell: cmd
        if: ${{ matrix.os == 'windows-2019' }}
        run: >-
          "C:\Program Files (x86)\Microsoft Visual
          Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
          nativeImage
        env:
          JAVA_OPTS: -Xmx1g
      - uses: actions/upload-artifact@master
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
      - name: Upload release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ matrix.local_path }}
          asset_name: ${{ matrix.uploaded_filename }}
          asset_content_type: application/zip
